Repository ADOdb/ADOdb, pull requests merged in 2022-01, with the labels that each got.

#783 Prevent PHP warning if P1 or P2 happen to be an array.
  adodb-exceptions.inc.php
Labels: bug, core

#782 Add PostgreSQL standard datatypes for UUID, NUMERIC, DECIMAL, FLOAT4 …
  drivers/adodb-postgres64.inc.php
Labels: enhancement, pgsql

#794 Add phpDocumentor3 configuration
  .gitignore
  adodb-datadict.inc.php
  adodb-xmlschema.inc.php
  adodb-xmlschema03.inc.php
  datadict/datadict-postgres.inc.php
  drivers/adodb-firebird.inc.php
  drivers/adodb-mysqli.inc.php
  drivers/adodb-oci8.inc.php
  perf/perf-mysql.inc.php
  perf/perf-postgres.inc.php
  phpdoc.dist.xml
Labels: meta, documentation
